return {}
-- return {
-- 	"neovim/nvim-lspconfig",
-- 	event = { "BufReadPre", "BufNewFile" },
-- 	dependencies = {
-- 		{ "folke/neodev.nvim", opts = {} },
-- 		"saghen/blink.cmp",
-- 	},
-- 	config = function()
--
-- 		-- for _, server in ipairs({
-- 		-- 	"dockerls",
-- 		-- 	"docker_compose_language_service",
-- 		-- 	"ts_ls",
-- 		-- 	"html",
-- 		-- 	"cssls",
-- 		-- 	"bashls",
-- 		-- 	"marksman",
-- 		-- 	"jedi_language_server",
-- 		-- 	"sqlls",
-- 		-- }) do
-- 		-- 	lspconfig[server].setup({ capabilities = capabilities })
-- 		-- end
-- 		-- lspconfig.emmet_ls.setup({
-- 		-- 	capabilities = capabilities,
-- 		-- 	filetypes = {
-- 		-- 		"css",
-- 		-- 		"html",
-- 		-- 		"less",
-- 		-- 		"sass",
-- 		-- 		"scss",
-- 		-- 		"htmldjango",
-- 		-- 	},
-- 		-- })
-- 	end,
-- }
