import = [
  "~/.config/alacritty/themes/themes/kanagawa_wave.toml"
]

[env]
TERM = "xterm-256color"

[font]
size=12.0

[font.bold]
family = "JetBrainsMono Nerd Font"
# family = "xos4 Terminus"
# family = "Terminess Nerd Font Mono"
# family  = "IosevkaTerm Nerd Font Mono"
# family = "Hack Nerd Font"
# family = "DeJaVuSansM Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
# family = "Terminess Nerd Font Mono"
# family = "Hack Nerd Font"
# family  = "IosevkaTerm Nerd Font Mono"
# family = "DeJaVuSansM Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
# family = "Terminess Nerd Font Mono"
# family = "Hack Nerd Font"
# family  = "IosevkaTerm Nerd Font Mono"
# family = "DeJaVuSansM Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
# family  = "IosevkaTerm Nerd Font Mono"
# family = "xos4 Terminus"
# family = "Terminess Nerd Font Mono"
# family = "Hack Nerd Font"
# family = "DeJaVuSansM Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 4

[selection]
save_to_clipboard = true

[window]
decorations = 'buttonless'
opacity = 0.8
blur = true
# startup_mode = 'Maximized'
