vim.lsp.set_log_level("warn")
vim.cmd("packadd cfilter")
require("config.options")
require("config.autocmds")
require("config.usercmds")
require("config.keymaps")
require("core.lazy")
require("core.lsp")

require("diagnostics").setup()
require("highlights").setup()
